import {Color} from '@/definitions/color';
import {Class} from '@/entity/class';
import {CircleMove} from '@/entity/controller';
import {Vector} from '@/physics/vector';

Class.Food = {
    label: 'Square',
    sides: 4,
    size: 10,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: false,
    skill: {
        speed: 0.2,
        health: 5,
        regen: 0.0001,
        damage: 1,
        pen: 1,
        range: null,
        pushability: 1,
    },
    upgrades: ['Basic'],
    score: 100,
    food: true,
    miniMapType: 'none',
    guns: [],
    color: Color.Gold,
    controllers: [new CircleMove()],
};

Class.Pentagon = {
    parent: 'Food',
    label: 'Pentagon',
    sides: 5,
    size: 15,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 60,
        regen: 0.001,
        damage: 1,
        pen: 1,
        range: null,
        pushability: 1,
    },
    score: 600,
    food: true,
    guns: [],
    color: Color.Lavender,
    controllers: [new CircleMove()],
};

Class.ShinyPentagon = {
    parent: 'Food',
    label: 'Shiny Pentagon',
    sides: 5,
    size: 15,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 60,
        regen: 0.001,
        damage: 1,
        pen: 1,
        range: null,
        pushability: 1,
    },
    score: 10000,
    food: true,
    guns: [],
    color: Color.LightGreen,
    controllers: [new CircleMove()],
};

Class.AlphaPentagon = {
    parent: 'Food',
    label: 'Alpha Pentagon',
    sides: 5,
    size: 20,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 190,
        regen: 0.001,
        damage: 1,
        pen: 1,
        range: null,
        pushability: 1,
    },
    props: [
        {
            offset: new Vector(0, 0),
            layer: 10,
            fixedAngle: false,
            size: 15,
            color: Color.Lavender,
            alpha: 1,
            sides: 5,
            angle: Math.PI,
        },
        {
            offset: new Vector(0, 0),
            layer: 10,
            fixedAngle: false,
            size: 12,
            color: Color.Lavender,
            alpha: 1,
            sides: 5,
            angle: Math.PI * 2,
        },
    ],
    score: 2000,
    food: true,
    guns: [],
    color: Color.Lavender,
    controllers: [new CircleMove()],
};
