import {Color} from '@/definitions/color';
import {Class} from '@/entity/class';
import {CircleMove, ControllerMaker} from '@/entity/controller';
import {Vector} from '@/physics/vector';

Class.Food = {
    label: 'Square',
    sides: 4,
    size: 10,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: false,
    skill: {
        speed: 0.2,
        health: 5,
        regen: 0.0001,
        damage: 1,
        pen: 1,
        range: null,
        pushability: 1,
    },
    upgrades: ['Basic'],
    score: 100,
    food: true,
    miniMapType: 'none',
    guns: [],
    color: Color.Gold,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.Triangle = {
    parent: 'Food',
    label: 'Triangle',
    sides: 3,
    size: 10,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: false,
    skill: {
        speed: 0.2,
        health: 30,
        regen: 0.001,
        damage: 1,
        pen: 1,
        range: null,
        pushability: 1,
    },
    score: 300,
    food: true,
    guns: [],
    color: Color.Orange,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.Pentagon = {
    parent: 'Food',
    label: 'Pentagon',
    sides: 5,
    size: 15,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 60,
        regen: 0.001,
        damage: 2,
        pen: 1,
        range: null,
        pushability: 1,
    },
    score: 600,
    food: true,
    guns: [],
    color: Color.Lavender,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.Hexagon = {
    parent: 'Food',
    label: 'Hexagon',
    sides: 6,
    size: 15,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 60 * 3,
        regen: 0.001,
        damage: 2,
        pen: 1,
        range: null,
        pushability: 1,
    },
    score: 600 * 1.8,
    food: true,
    guns: [],
    color: Color.Aqua,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.ShinyPentagon = {
    parent: 'Food',
    label: 'Shiny Pentagon',
    sides: 5,
    size: 15,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 60,
        regen: 0.001,
        damage: 3,
        pen: 1,
        range: null,
        pushability: 1,
    },
    score: 10000,
    food: true,
    guns: [],
    color: Color.LightGreen,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.AlphaPentagon = {
    parent: 'Food',
    label: 'Alpha Pentagon',
    sides: 5,
    size: 20,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 60 * 9,
        regen: 0.001,
        damage: 3,
        pen: 1,
        range: null,
        pushability: 1,
    },
    props: [
        {
            offset: new Vector(0, 0),
            layer: 10,
            fixedAngle: false,
            size: 15,
            color: Color.Lavender,
            alpha: 1,
            sides: 5,
            angle: Math.PI,
        },
        {
            offset: new Vector(0, 0),
            layer: 10,
            fixedAngle: false,
            size: 12,
            color: Color.Lavender,
            alpha: 1,
            sides: 5,
            angle: Math.PI * 2,
        },
    ],
    score: 2000,
    food: true,
    guns: [],
    color: Color.Lavender,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.AlphaTriangle = {
    parent: 'Food',
    label: 'Alpha Triangle',
    sides: 3,
    size: 20,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 190,
        regen: 0.001,
        damage: 1,
        pen: 1,
        range: null,
        pushability: 1,
    },
    props: [
        {
            offset: new Vector(0, 0),
            layer: 10,
            fixedAngle: false,
            size: 10,
            color: Color.Orange,
            alpha: 1,
            sides: 3,
            angle: Math.PI,
        },
        {
            offset: new Vector(0, 0),
            layer: 5,
            fixedAngle: false,
            size: 4,
            color: Color.Orange,
            alpha: 1,
            sides: 3,
            angle: Math.PI * 2,
        },
    ],
    score: 2000,
    food: true,
    guns: [],
    color: Color.Orange,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.MonsterTriangle = {
    parent: 'Food',
    label: 'Monster Triangle',
    sides: 3,
    size: 20,
    showHealth: true,
    showName: false,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 340,
        regen: 0.001,
        damage: 2,
        pen: 1,
        range: null,
        pushability: 1,
    },
    props: [
        {
            offset: new Vector(0, 0),
            layer: 10,
            fixedAngle: false,
            size: 15,
            color: Color.Orange,
            alpha: 1,
            sides: 3,
            angle: Math.PI,
        },
        {
            offset: new Vector(0, 0),
            layer: 10,
            fixedAngle: false,
            size: 12,
            color: Color.Orange,
            alpha: 1,
            sides: 3,
            angle: Math.PI * 2,
        },
    ],
    score: 200000,
    food: true,
    guns: [],
    color: Color.Orange,
    controllers: [new ControllerMaker(CircleMove)],
};

Class.King = {
    parent: 'Food',
    label: 'King',
    name: 'King',
    sides: 6,
    size: 20,
    showHealth: true,
    showName: true,
    showScore: false,
    giveScore: true,
    killMessage: true,
    skill: {
        speed: 0.2,
        health: 340,
        regen: 0.001,
        damage: 2,
        pen: 1,
        range: null,
        pushability: 1,
    },
    score: 200000,
    food: true,
    guns: [],
    color: Color.Orange,
    controllers: [new ControllerMaker(CircleMove)],
};
